create table regist (
   num int not null auto_increment,
   id char(20) not null,
   name  char(20) not null,
   address  char(100) not null,
   kind char(50) not null,
   type char(20) not null,
   ctype char(50) not null,
   deposit char(20) not null,
   rent char(20) not null,
   superfree char(20) not null,
   day char(20) ,
   fac1 char(10) ,
   fac2 char(10) ,
   fac3 char(10) ,
   fac4 char(10) ,
   rname char(50) not null,
   current int default '0',
   contents text not null,
   regist_day char(20),
   file_name_0 char(40),
   file_name_1 char(40),
   file_name_2 char(40),
   file_name_3 char(40),
   file_name_4 char(40),
   file_copied_0 char(30),
   file_copied_1 char(30),
   file_copied_2 char(30),
   file_copied_3 char(30),
   file_copied_4 char(30), 
   primary key(num)
);